### ISSUE TITLE
Latest APT version (1.6.1) far behind Git repo

### ISSUE THREAD

**Issue by creeper6530** [azlux/log2ram#218]
Please, would you release a new version with all the improvements from the Git version? I'd especially like to have journald awareness, but I can't install anything other than via APT

**Comment by jult** [comment]
Yes, please. Another vote to up the apt for debian bookworm.

**Comment by onlineapps-cloud** [comment]
i added my vote

**Comment by BugBuster1701** [comment]
Yes, please release a new version.

**Comment by adamsthws** [comment]
I would like to kindly echo this request too.

**Comment by azlux** [comment]
Hi all,

Since people request for a new release, I need to adapt the project state to the new need.
Since I'm busy with other stuff, I do less computer/coding. And I don't have raspberry with sd cart anymore (only ssd) with log2ram.

What I propose, I will make a beta release for log2ram, and propose a vote ? / feedback ? on it.
If (let's say) five peoples approve the beta, I will merge to stable one week later.

What do you think ?
I want to avoid a new [xz](https://www.docker.com/blog/openssh-and-xz-liblzma/) problem.

Az

**Comment by adamsthws** [comment]
Thankyou Az, that would be super!I'd be happy to undertake testing. 
Is there a changelog so we know where to focus the testing efforts?

**Comment by azlux** [comment]
Let's test the new version with https://github.com/azlux/log2ram/releases/tag/1.7b1 available in testing (sid) codename

**Comment by adamsthws** [comment]
> Let's test the new version with https://github.com/azlux/log2ram/releases/tag/1.7b1 available in testing (sid) codename

I'm happy to report no major issues!

The only minor issue I found was that the Ansible playbook needed updating:
[(Pull Request 225)](https://github.com/azlux/log2ram/pull/225)

Other than that, all working well for me :)

**Comment by adamsthws** [comment]
Hi Az, 

With the new beta needing testers, do you think it might be a good idea to make a post on Reddit (r/raspberry_pi?) requesting as such?

I'd be happy to compose the Reddit post. Though I understand you're currently on holiday so maybe not this week.

Cheers,
Adam
