### ISSUE TITLE
possibly dead code in install script?

### ISSUE THREAD

**Issue by thomas-mc-work** [azlux/log2ram#43]
Do these lines make any sense?

https://github.com/azlux/log2ram/blob/e88f67ab23a91bb1482f0f2063b990585b27730c/install.sh#L21-L27

Respectively will they every be executed? Because the lines 3 &4 actually prevent from continuing the script to this point.

https://github.com/azlux/log2ram/blob/e88f67ab23a91bb1482f0f2063b990585b27730c/install.sh#L3-L4

**Comment by azlux** [comment]
Hi,
The first part (line 21 to 27) is here to remove the folder of a previous installation (hdd.log) , I also remove log.hdd because it's come from a previous version of log2ram
You can check my review of #37 
The second part (line 3-4) check if log2ram is already install. I've add this part after the previous one.
So, you're right, the lines 25 to 27 is useless.
